using System;

namespace LeapingGorilla.Testing.Exceptions
{
	public class OnlyInterfacesMayBeAutoGeneratedAsDependenciesException : ApplicationException
	{
		public OnlyInterfacesMayBeAutoGeneratedAsDependenciesException(Type typeToFake)
			: base(
				String.Format(
					"The type {0} cannot be used as an auto-generated dependency or mock as it is not an interface. You must manually set a value for this dependency by overriding CreateManualDependencies.",
					typeToFake))
		{
			
		}
	}
}
