/*    
   Copyright 2014 Leaping Gorilla LTD

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
using System;

namespace LeapingGorilla.Testing.Exceptions
{
	public class OnlyInterfacesMayBeAutoGeneratedAsDependenciesException : ApplicationException
	{
		public OnlyInterfacesMayBeAutoGeneratedAsDependenciesException(Type typeToFake)
			: base(
				String.Format(
					"The type {0} cannot be used as an auto-generated dependency or mock as it is not an interface. You must manually set a value for this dependency by overriding CreateManualDependencies.",
					typeToFake))
		{
			
		}
	}
}
